import localFont from "next/font/local";
import "./globals.css";
import P from "./NewMem/P";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-gray-100"
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div>
          <P></P>
        </div>
        
        <div className="m-2">
          
        {children}
        </div>
       
      </body>
    </html>
  );
}
